# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PDF-API2
version:      0.51
version_from: lib/PDF/API2/Version.pm
installdirs:  site
requires:
    Compress::Zlib:                1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
