#!/usr/bin/perl
#=======================================================================
#    ____  ____  _____              _    ____ ___   ____
#   |  _ \|  _ \|  ___|  _   _     / \  |  _ \_ _| |___ \
#   | |_) | | | | |_    (_) (_)   / _ \ | |_) | |    __) |
#   |  __/| |_| |  _|    _   _   / ___ \|  __/| |   / __/
#   |_|   |____/|_|     (_) (_) /_/   \_\_|  |___| |_____|
#
#   A Perl Module Chain to faciliate the Creation and Modification
#   of High-Quality "Portable Document Format (PDF)" Files.
#
#   Copyright 1999-2007 Alfred Reibenschuh <areibens@cpan.org>.
#
#=======================================================================
#
#   PERMISSION TO USE, COPY, MODIFY, AND DISTRIBUTE THIS FILE FOR
#   ANY PURPOSE WITH OR WITHOUT FEE IS HEREBY GRANTED, PROVIDED THAT
#   THE ABOVE COPYRIGHT NOTICE AND THIS PERMISSION NOTICE APPEAR IN ALL
#   COPIES.
#
#   THIS FILE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED
#   WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#   MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
#   IN NO EVENT SHALL THE AUTHORS AND COPYRIGHT HOLDERS AND THEIR
#   CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
#   LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
#   USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
#   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
#   OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
#   OF THE USE OF THIS FILE, EVEN IF ADVISED OF THE POSSIBILITY OF
#   SUCH DAMAGE.
#
#   $Id$
#
#=======================================================================
use lib '../lib';
use PDF::API2;
use PDF::API2::Util;

$pdf=PDF::API2->new;
$f1=$pdf->corefont('Verdana');

$page = $pdf->page;
$page->mediabox(595,842);
$gfx=$page->gfx;
$gfx->textlabel(50,780,$f1,20,"Hello World!");

$pdf->saveas("$0.BASE.pdf");
$pdf->end();

$pdf=PDF::API2->open("$0.BASE.pdf");
$f1=$pdf->corefont('Verdana');

$page = $pdf->page;
$page->mediabox(595,842);
$gfx=$page->gfx;
$gfx->textlabel(50,780,$f1,20,"Hello World! (2)");

$pdf->saveas("$0.UPDATED.pdf");
$pdf->end();

$pdf=PDF::API2->open("$0.UPDATED.pdf");
$f1=$pdf->corefont('Verdana');

$page = $pdf->page;
$page->mediabox(595,842);
$gfx=$page->gfx;
$gfx->textlabel(50,780,$f1,20,"Hello World! (3)");

$str=$pdf->stringify();
$pdf->end();

$pdf=PDF::API2->openScalar($str);
$f1=$pdf->corefont('Verdana');

$page = $pdf->page;
$page->mediabox(595,842);
$gfx=$page->gfx;
$gfx->textlabel(50,780,$f1,20,"Hello World! (4)");

$pdf->saveas("$0.STRING.pdf");
$pdf->end();





exit;

__END__
