#!/usr/bin/perl

use PDF::API2;
use PDF::API2::Util;


$pdf=PDF::API2->new;

$f1=$pdf->corefont('Helvetica',-encode=>'latin1');
$f2=$pdf->corefont('Helvetica-Bold',-encode=>'latin1');

$page = $pdf->page;
$page->mediabox(595,842);

$txt=$page->text;
$txt->font($f1,20);

$txt->translate(50,800);
$txt->text('normal text');
$txt->rise(5);
$txt->text('rise = 5 units');
$txt->rise(-5);
$txt->text('rise = -5 units');
$txt->rise(0);

$txt->translate(50,600);
$txt->text('normal text');
$txt->rise(10);
$txt->text('rise = 10 units');
$txt->rise(-10);
$txt->text('rise = -10 units');
$txt->rise(0);

$txt->translate(50,400);
$txt->text('normal text');
$txt->rise(20);
$txt->text('rise = 20 units');
$txt->rise(-20);
$txt->text('rise = -20 units');
$txt->rise(0);

$pdf->saveas("$0.pdf");
$pdf->end();

exit;

__END__
