#!/usr/bin/perl

use lib '../lib';
use PDF::API2;
use PDF::API2::Util;

my $sx=33;
my $sy=45;
my $fx=20;

@lorem = qw{
Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nunc consectetuer fermentum est. Vivamus arcu lacus, aliquam ac, congue in, mollis quis, nunc. Curabitur in metus. Maecenas id dolor quis ante fermentum rhoncus. Maecenas pulvinar lacus ut nisi. Morbi metus. Morbi commodo, enim at venenatis venenatis, turpis orci feugiat libero, sed elementum est enim quis eros. Sed ultrices neque nec nibh. Pellentesque accumsan condimentum dui. Curabitur vestibulum. Fusce pede nibh, ullamcorper ac, sollicitudin nec, blandit sit amet, sem. Mauris libero. Duis ligula sem, imperdiet dictum, gravida ac, placerat ut, dolor. Vestibulum condimentum, lacus et venenatis tristique, augue erat fringilla metus, in venenatis ipsum nibh non purus. In at justo eget elit elementum tempor. Cras et urna. Suspendisse potenti.
Quisque commodo neque in eros. Donec dictum congue augue. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Vestibulum dictum dignissim pede. Proin rhoncus, tellus ut interdum tincidunt, felis neque vehicula nulla, non euismod purus mi ut risus. Sed ac metus. Praesent dignissim convallis metus. Cras eu nisl vel purus cursus dignissim. Proin eu libero. Nulla facilisi.
Ut laoreet eros quis tortor. Donec suscipit dolor ut sapien. Aliquam facilisis molestie tortor. Ut eu lorem a velit elementum suscipit. Aliquam erat volutpat. Curabitur sed elit. Donec consectetuer urna. Duis vel eros eget nulla commodo eleifend. Vestibulum fermentum egestas felis. Nullam risus nibh, auctor eget, facilisis non, consectetuer a, lectus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In hac habitasse platea dictumst. Quisque vitae ligula. Nulla risus. Aliquam luctus sapien at ipsum.
Maecenas mauris ante, hendrerit consequat, lacinia et, condimentum vel, arcu. Proin egestas. Sed a dui luctus nisi sodales ornare. Mauris tristique augue ut elit. Integer rutrum, mauris eu imperdiet tincidunt, tellus neque rutrum sapien, nec lacinia augue pede a risus. Vivamus in dolor id erat volutpat ornare. Pellentesque pellentesque. Nunc dignissim, tortor vitae posuere aliquam, mi velit ultricies magna, et egestas neque eros sed urna. Proin aliquet fermentum tortor. Quisque vitae elit at turpis lobortis interdum. In hac habitasse platea dictumst.
Nam sagittis congue dolor. Ut eleifend, urna id dignissim scelerisque, ante risus malesuada odio, id sodales mauris elit at nisi. In nisi turpis, imperdiet eget, vestibulum a, semper vel, lacus. Donec sed lorem. Quisque laoreet purus consequat purus. Curabitur auctor felis. Fusce faucibus cursus arcu. Proin gravida hendrerit justo. Aenean aliquam suscipit pede. Curabitur varius elit in ligula. In dignissim imperdiet nulla. Integer interdum, odio id venenatis lacinia, tortor sem auctor risus, ac malesuada velit sapien vitae lacus. Quisque in nulla. Morbi mattis turpis molestie eros. Sed massa est, sollicitudin non, eleifend egestas, adipiscing gravida, sem. Curabitur sagittis massa dignissim sapien.
Proin accumsan, quam luctus vestibulum tincidunt, erat metus porta pede, sit amet viverra elit lorem nec dolor. Aliquam magna. Phasellus pellentesque. Nullam cursus. Morbi nisl urna, commodo id, elementum lobortis, malesuada at, nulla. Aliquam faucibus nunc vehicula velit. Nunc cursus pede ac lectus. Sed faucibus nisi vitae nisl. Vivamus eget leo. Nulla ante sapien, convallis convallis, pulvinar ac, ultrices at, est. Donec a massa. Phasellus dui arcu, varius vel, egestas quis, convallis sed, pede. Quisque eget nulla vel nisi tincidunt sodales. Proin leo. Ut sapien.
Ut consequat. Fusce quis nulla in velit eleifend imperdiet. Sed vestibulum ultricies nulla. Ut tellus velit, lobortis eu, commodo eget, dapibus ac, libero. Etiam lacinia, justo vel rhoncus placerat, arcu ante lacinia tellus, ac blandit lacus mauris ut urna. Phasellus suscipit nulla vitae mi. In elit. Nulla venenatis, arcu vitae rhoncus accumsan, nisl lectus laoreet tortor, nec sollicitudin est purus in erat. Pellentesque dignissim pede eget orci. Aenean fringilla mattis felis. Quisque quis odio eu pede pretium congue.
Pellentesque id nibh sit amet ipsum eleifend rhoncus. Morbi gravida. Vestibulum ut arcu aliquet est blandit aliquam. Nulla justo eros, rutrum ac, ornare a, consequat non, orci. Suspendisse potenti. Integer eleifend sapien id mauris. Nullam egestas, lacus vitae feugiat tempus, mi nisl bibendum diam, et scelerisque quam enim id enim. Nunc vel massa. Pellentesque id arcu id velit dapibus eleifend. Integer cursus mollis est. Praesent scelerisque nulla eget sem. Integer vel magna eget dolor ornare eleifend.
Vivamus pede orci, vehicula quis, sagittis dignissim, accumsan quis, est. Sed molestie lorem sed metus. Phasellus consequat rhoncus mauris. Vivamus pede velit, placerat vel, sollicitudin id, imperdiet a, massa. Vestibulum laoreet, metus vitae semper convallis, ante turpis convallis justo, nec varius velit mauris eu ante. Suspendisse potenti. Aliquam sollicitudin dignissim nisl. Aliquam lectus. Mauris eu lectus quis metus fringilla interdum. Nullam mattis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam sapien mauris, euismod et, porttitor non, hendrerit quis, elit. In turpis. Duis tempor, lectus vel iaculis iaculis, lacus est elementum ligula, vitae pulvinar mi magna sit amet felis.
Nam ultricies tellus eget felis. Sed sapien. Donec vitae enim. Ut eu magna. Proin interdum nisi id nunc. Maecenas ullamcorper. Praesent sem. Ut eu leo et augue lobortis fringilla. Phasellus eget ligula et massa varius iaculis. Praesent mauris metus, laoreet ac, varius at, sollicitudin ac, quam. Suspendisse enim diam, facilisis convallis, egestas eget, placerat quis, diam. Donec vel nunc eu dolor mollis bibendum. Aenean facilisis. 
};

    $pdf=PDF::API2->new;
    $f1=$pdf->corefont('Helvetica',-encode => 'latin1');
    my $fnt=$pdf->ttfont('../lib/PDF/API2/fonts/DejaVuSans.ttf',-encode => 'latin1');

    foreach my $k ({-slant=>0.750},{-oblique=>12},{-bold=>4},{-caps=>1}) {

        my $font=$pdf->synfont($fnt, %{$k});

        my $page = $pdf->page;
        $page->mediabox(595,842);

        my $txt=$page->text;
        $txt->font($font,$fx);

        my $u=$font->underlineposition*$fx/1000;

        my $text=join(' ', @lorem);

        my $y=800;
        while($y>50 && length($text)>0)
        {
            $txt->translate(50,$y);
            ($w, $text) = $txt->text_fill_justified($text,500);
            $y-=$fx*1.15;
        }
    }
    
    $pdf->saveas("$0.pdf");
    $pdf->end();

__END__
