#!/usr/bin/perl
#=======================================================================
#    ____  ____  _____              _    ____ ___   ____
#   |  _ \|  _ \|  ___|  _   _     / \  |  _ \_ _| |___ \
#   | |_) | | | | |_    (_) (_)   / _ \ | |_) | |    __) |
#   |  __/| |_| |  _|    _   _   / ___ \|  __/| |   / __/
#   |_|   |____/|_|     (_) (_) /_/   \_\_|  |___| |_____|
#
#   A Perl Module Chain to faciliate the Creation and Modification
#   of High-Quality "Portable Document Format (PDF)" Files.
#
#   Copyright 1999-2004 Alfred Reibenschuh <areibens@cpan.org>.
#
#=======================================================================
#
#   PERMISSION TO USE, COPY, MODIFY, AND DISTRIBUTE THIS FILE FOR
#   ANY PURPOSE WITH OR WITHOUT FEE IS HEREBY GRANTED, PROVIDED THAT
#   THE ABOVE COPYRIGHT NOTICE AND THIS PERMISSION NOTICE APPEAR IN ALL
#   COPIES.
#
#   THIS FILE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED
#   WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#   MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
#   IN NO EVENT SHALL THE AUTHORS AND COPYRIGHT HOLDERS AND THEIR
#   CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
#   LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
#   USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
#   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
#   OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
#   OF THE USE OF THIS FILE, EVEN IF ADVISED OF THE POSSIBILITY OF
#   SUCH DAMAGE.
#
#   $Id$
#
#=======================================================================

use PDF::API2;
use PDF::API2::Util;
use POSIX;
use Math::Trig;

my $cx=50;
my $cy=50;
my $cr=15;
my $cs=30;
my $ang=30;

$pdf=PDF::API2->new;
$pdf->mediabox(595,842);

$fnt=$pdf->corefont('Verdana-Bold');

    $page = $pdf->page;
    $gfx=$page->gfx;
    
    $gfx->textlabel(300,750,$fnt,20,'Separation Colorspace(s)',-color=>'#000',-hspace=>125,-center=>1);

    $gfx->strokecolor('#000');
    my $y=0;
    foreach my $csn (qw( Red %0ff0 Green %f0f0 Blue %ff00 Cyan %f000 Magenta %0f00 Yellow %00f0 )) {
        my $csp=$pdf->colorspace_separation($csn,$csn);
        $gfx->textlabel($cx,$cy+($y*$cs),$fnt,8,$csn,-color=>'#000',-hspace=>85,-right=>1);
        foreach my $x (0 .. 0xf) {
            $gfx->fillcolor($csp,sprintf('%0.4f',$x/0xf));
            $gfx->circle($cx+($x+1)*$cs,$cy+($y+0.5)*$cs,$cr);
            $gfx->fillstroke;
            $gfx->textlabel($cx+($x+1)*$cs,$cy+($y+0.5)*$cs,$fnt,8,sprintf('%0.4f',$x/0xf),-color=>'#000',-hspace=>85,-center=>1);
        }
        $y++;
    }


    my $csp=$pdf->colorspace_separation('All','#000');
    $gfx->textlabel($cx,$cy+($y*$cs),$fnt,8,'All',-color=>'#000',-hspace=>85,-right=>1);
    foreach my $x (0 .. 0xf) {
        $gfx->fillcolor($csp,sprintf('%0.4f',$x/0xf));
        $gfx->circle($cx+($x+1)*$cs,$cy+($y+0.5)*$cs,$cr);
        $gfx->fillstroke;
        $gfx->textlabel($cx+($x+1)*$cs,$cy+($y+0.5)*$cs,$fnt,8,sprintf('%0.4f',$x/0xf),-color=>'#000',-hspace=>85,-center=>1);
    }
    $y++;

    $csp=$pdf->colorspace_separation('None','#000');
    $gfx->textlabel($cx,$cy+($y*$cs),$fnt,8,'None',-color=>'#000',-hspace=>85,-right=>1);
    foreach my $x (0 .. 0xf) {
        $gfx->fillcolor($csp,sprintf('%0.4f',$x/0xf));
        $gfx->circle($cx+($x+1)*$cs,$cy+($y+0.5)*$cs,$cr);
        $gfx->fillstroke;
        $gfx->textlabel($cx+($x+1)*$cs,$cy+($y+0.5)*$cs,$fnt,8,sprintf('%0.4f',$x/0xf),-color=>'#000',-hspace=>85,-center=>1);
    }
    $y++;

    delete $gfx->{Filter};

$pdf->saveas("$0.pdf");
$pdf->end();

exit;

__END__

    