#!/usr/bin/perl

use lib '../lib';
use PDF::API2;
use PDF::API2::Util;


$pdf=PDF::API2->new;

$f1=$pdf->corefont('Helvetica',-encode=>'latin1');
$f2=$pdf->corefont('Helvetica-Bold',-encode=>'latin1');

foreach my $i (0 .. 25)
{
	$page = $pdf->page;
	$page->mediabox(595,842);
	
	$gfx=$page->gfx;
	$gfx->textlabel(50,700,$f2,20,'Page Index='.$i);
}

$pdf->pageLabel(0, { -style => 'Roman' });

$pdf->pageLabel(4, { -start => 1 });

$pdf->pageLabel(14, { -start => 1, -prefix => 'A-' });
$pdf->pageLabel(16, { -start => 1, -prefix => 'B-' });
$pdf->pageLabel(18, { -start => 1, -prefix => 'C-' });

$pdf->pageLabel(20, { -start => 10 });

$pdf->pageLabel(23, { -style => 'Alpha' });


$pdf->saveas("$0.pdf");
$pdf->end();

exit;

__END__
