#!/usr/bin/perl
#=======================================================================
#    ____  ____  _____              _    ____ ___   ____
#   |  _ \|  _ \|  ___|  _   _     / \  |  _ \_ _| |___ \
#   | |_) | | | | |_    (_) (_)   / _ \ | |_) | |    __) |
#   |  __/| |_| |  _|    _   _   / ___ \|  __/| |   / __/
#   |_|   |____/|_|     (_) (_) /_/   \_\_|  |___| |_____|
#
#   A Perl Module Chain to faciliate the Creation and Modification
#   of High-Quality "Portable Document Format (PDF)" Files.
#
#   Copyright 1999-2004 Alfred Reibenschuh <areibens@cpan.org>.
#
#=======================================================================
#
#   PERMISSION TO USE, COPY, MODIFY, AND DISTRIBUTE THIS FILE FOR
#   ANY PURPOSE WITH OR WITHOUT FEE IS HEREBY GRANTED, PROVIDED THAT
#   THE ABOVE COPYRIGHT NOTICE AND THIS PERMISSION NOTICE APPEAR IN ALL
#   COPIES.
#
#   THIS FILE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED
#   WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#   MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
#   IN NO EVENT SHALL THE AUTHORS AND COPYRIGHT HOLDERS AND THEIR
#   CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#   SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
#   LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
#   USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
#   ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
#   OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
#   OF THE USE OF THIS FILE, EVEN IF ADVISED OF THE POSSIBILITY OF
#   SUCH DAMAGE.
#
#   $Id$
#
#=======================================================================
use lib '../lib/';
use PDF::API2;
use PDF::API2::Util;
use POSIX;


$pdf=PDF::API2->new;
$pdf->mediabox(595,842);

my $TRANSPARENT = $pdf->egstate; # Called just once
$TRANSPARENT->transparency(0.9);

$fnt=$pdf->corefont('Verdana-Bold');

$page = $pdf->page;
$gfx=$page->gfx;

$gfx->textlabel(30,750,$fnt,100,'100% Opaque',-color=>'#F00');

$gfx->save;
$gfx->egstate( $TRANSPARENT );
$gfx->textlabel(30,720,$fnt,100,'90% Transparent',-color=>'#000');
$gfx->restore;

$page = $pdf->page;
$text=$page->text;

$text->save;
$text->font( $fnt, 100 );
$text->fillcolor( 'red' );
$text->translate( 570, 750 );
$text->text_right( 'Opaque 100%' );
$text->fill;
$text->restore;

$text->textend;
$text->save;
$text->egstate( $TRANSPARENT );
$text->textstart;
$text->font( $fnt, 100 );
$text->fillcolor( 'black' );
$text->translate( 570, 720 );
$text->text_right( 'Transparent 90%' );
$text->fill;
$text->textend;
$text->restore;
$text->textstart;

$pdf->saveas("$0.pdf");
$pdf->end();

exit;

__END__

    