#=======================================================================
#         _   _    :    ____  ____  _____      _    ____ ___   ____
#     _  |_|_|_|   :   |  _ \|  _ \|  ___|    / \  |  _ \_ _| |___ \
#    |_| _|_||_|   :   | |_) | | | | |_      / _ \ | |_) | |    __) |
#    _  |_||_|_|   :   |  __/| |_| |  _|    / ___ \|  __/| |   / __/
#   |_|  |_|_|_|   :   |_|   |____/|_|     /_/   \_\_|  |___| |_____|
#                  : 
#=======================================================================
package PDF::API2::Version;
BEGIN {
    use vars qw( $VERSION %CVersion );
    $VERSION = '0.72';
    %CVersion = (
        'vFredo' => 'PDF::API2 0.72',
        'vHex' => '0x00048000',
        'vLong' => '0.72',
        'vPerl' => '0.72',
        'vShort' => '0.72',
        'vWeb' => 'PDF::API2/0.72',
    );
}
1;

__END__
# autogenerated file -- do not edit.

=pod

=head1 NAME

PDF::API2::Version

=head1 VERSION

  vFredo: PDF::API2 0.72 
    vHex: 0x00048000 
   vLong: 0.72 
   vPerl: 0.72 
  vShort: 0.72 
    vWeb: PDF::API2/0.72 

=cut

