#=======================================================================
#         _   _    :    ____  ____  _____      _    ____ ___   ____
#     _  |_|_|_|   :   |  _ \|  _ \|  ___|    / \  |  _ \_ _| |___ \
#    |_| _|_||_|   :   | |_) | | | | |_      / _ \ | |_) | |    __) |
#    _  |_||_|_|   :   |  __/| |_| |  _|    / ___ \|  __/| |   / __/
#   |_|  |_|_|_|   :   |_|   |____/|_|     /_/   \_\_|  |___| |_____|
#                  : 
#=======================================================================
package PDF::API2::Version;
BEGIN {
    use vars qw( $VERSION %CVersion );
    $VERSION = '0.51';
    %CVersion = (
        'vFredo' => 'PDF::API2 0.51 (fix-3328 / 2005-11-16)',
        'vGNU' => 'PDF::API2 0.51 (2005-11-16 03:26:05)',
        'vHex' => '0x00033D00',
        'vLong' => '0.51 (2005-11-16 03:26:05)',
        'vPerl' => '0.51',
        'vShort' => '0.51',
        'vSquid' => '0.51-fix-3328',
        'vTeX' => 'This is PDF::API2, Version 0.51 (2005-11-16 03:26:05)',
        'vWeb' => 'PDF::API2/0.51',
        'vWin' => '0.51 build 3328',
    );
}
1;

__END__
# autogenerated file -- do not edit.

=pod

=head1 NAME

PDF::API2::Version

=head1 VERSION

  vFredo: PDF::API2 0.51 (fix-3328 / 2005-11-16) 
    vGNU: PDF::API2 0.51 (2005-11-16 03:26:05) 
    vHex: 0x00033D00 
   vLong: 0.51 (2005-11-16 03:26:05) 
   vPerl: 0.51 
  vShort: 0.51 
  vSquid: 0.51-fix-3328 
    vTeX: This is PDF::API2, Version 0.51 (2005-11-16 03:26:05) 
    vWeb: PDF::API2/0.51 
    vWin: 0.51 build 3328 

=cut

